### ISSUE TITLE
Deploy v1.2.0

### ISSUE THREAD

**Issue by LZygmunt** [kurczaczkowe-rzeczy/randomizator#58]
- [x] Click on form name cause copy the name #57 
- [x] Highlight form name on type in "captcha" field #59 
- [x] Copy text should be scrollable #60 
- [x] Draw from unique anwsers #61
